### ISSUE TITLE
LocaleSwitcher issue

### ISSUE THREAD

**Issue by FDT2k** [awcodes/filament-tiptap-editor#115]
Sorry, it's me again :smile: 

seems to be related to #85 

There is an issue with locale switcher (Custom one but with the same behavior than the original). When I switch the first time, nothing happens and the form is not filled with translated content , then when switching locales, translations are reversed.

```js
 this.$watch('locale', () => {
                setTimeout(() => {
                    editors[this.id].destroy();
                    this.initEditor(this.state);
                }, 1000);
            });
```

I increased the timeout to 1000ms and everything is ok. 

I think that the timeout is a bit too short and then the editor is filled with the previous state.   Only happen when the field is **not** used in Builder or Repeater.

**Comment by awcodes** [comment]
Thanks, yea, the timeout is a temporary fix and there's no way to get a good timing on it since it depends on a livewire call which could be any amount of time coming back from the sever. Looking into using livewire lifecycle hooks instead but haven't had time to really experiment with them yet. Thank you for your patience.
