### ISSUE TITLE
links use the same url

### ISSUE THREAD

**Issue by eduardonwa** [awcodes/filament-tiptap-editor#150]
when using two links on the same line both redirect to the same url. it happened as i placed the second link that i noticed the first link i had introduced suddenly changed to the last link i added. 

edit:
nevermind. it's the display of the URL that doesn't get updated. the links do work when placed within the same line, but it appears that you need to click on something else, like a word below to have it show the correct link.

**Comment by pboivin** [comment]
Hi @eduardonwa, which version are you on?

**Comment by eduardonwa** [comment]
Hi @pboivin Currently using * v2.6.3

**Comment by pboivin** [comment]
Thanks @eduardonwa, I can replicate the issue on the latest `2.6.5`. I'll try to look into it.

**Comment by awcodes** [comment]
The issue here is that without clicking somewhere else to destroy the tippy instance the data can't get reset. So clicking one link and then the other tippy instance doesn't get destroyed because the condition to show / hide it is that the active selection is a link. Need to do some more digging. I think it's a side effect of having to override the bubble menu script to make it work with the alpine tippy integration.
