### ISSUE TITLE
[v2] [tiptap warn]: Duplicate extension names found: ['bubbleMenu']. This can lead to issues.

### ISSUE THREAD

**Issue by lotarbo** [awcodes/filament-tiptap-editor#153]
Hi, i use tiptap field multiple times on the page, and this what i have in console in chrome
<img width="1597" alt="image" src="https://github.com/awcodes/filament-tiptap-editor/assets/1766890/42f2793a-fc24-4c64-bbc9-5315b03beecb">

**Comment by awcodes** [comment]
Yep. This is a bug in Tiptap. I'm hoping they solve it soon.

**Comment by eugenefvdm** [comment]
In my opinion this is a breaking change as it completely removed source code I put into code blocks, so that the next time I save in Filament PHP everything is gone. Do you have any clues or insight why this happens, e.g. the bug report?

EDIT:

I found references to StarterKit conflicts. I guess this is visible if I include no profile at all, then I see the Paragraph button:

```php
TiptapEditor::make('content')
                    ->tools([
                        'code-block'
```

Result (see paragraph which I didn't specify):

![Screenshot 2023-11-23 at 11 44 40](https://github.com/awcodes/filament-tiptap-editor/assets/1836436/6e832161-d03b-4f9f-a1f3-711514e53002)

I tried removing the `StarterKit` but that didn't work:

```php
return [
            new StarterKit([
                'paragraph' => false,
            ]),
```

References:

https://github.com/ueberdosis/tiptap/issues/2890#issuecomment-1579785550
https://github.com/ueberdosis/tiptap/discussions/3030
https://github.com/ueberdosis/tiptap/issues/2890
https://github.com/ueberdosis/tiptap/issues/3621

**Comment by awcodes** [comment]
The paragraph button is hard coded because there should always be a way to reset anything to the default state. So it alone doesn't honor the profiles or the tools.
