### ISSUE TITLE
Bubble menu actions is not working

### ISSUE THREAD

**Issue by fordiquez** [awcodes/filament-tiptap-editor#337]
### Filament Version

v.3.2.41

### Plugin Version

v3.2.25

### PHP Version

8.2.15

### Problem description

When selecting an action on the selected text from the bubble menu, the actions do not work (TypeError: editor(...).chain(...).focus(...).toggleStrike is not a function)\
[Loom video description](https://www.loom.com/share/c2743ba710c443f28c653cc7c638b313)

### Expected behavior

The selected action from the bubble menu is applied to the selected text

### Steps to reproduce

Install the plugin and initialize it in the Resource form:
```php
TiptapEditor::make('text')
        ->required()
        ->profile('minimal')
        ->output(TiptapOutput::Json)
```

**Comment by awcodes** [comment]
Are you seeing any console errors? I'm thinking this might be an alpine issue and not a plugin issue.

**Comment by chrismcintosh** [comment]
I've tried to use this plugin in two separate projects and ran into issues with the tip tap editor not allowing the toolbar actions to work (bold, underline)

1. An existing project
2. A project with only the bare minimum for this plugin to work so I could test in isolation

I was not able to get this plugin to work properly I might have missed something in documentation.

I opened a git project that replicates the issue here with a sqlite database already setup (from the second project) so that you can see the issue if you care to look into it - I saw there were a few other similar issues.

<img width="2056" alt="Screenshot 2024-03-02 at 1 36 22 PM" src="https://github.com/awcodes/filament-tiptap-editor/assets/2763551/f5d720f3-cf68-4e4b-b618-a2500bdc8bf6">

You should be able to login to filament using
**email**: admin@sample.com
**password:** password

https://github.com/chrismcintosh/filamenttiptap-editorissue

**Comment by awcodes** [comment]
![Screenshot 2024-03-02 at 4 07 11 PM](https://github.com/awcodes/filament-tiptap-editor/assets/3596800/b1900ca1-6453-439f-8078-f58558959c65)

Either use `->profile()` or `->tools()` don't use both. 😀

**Comment by chrismcintosh** [comment]
I'll give that a shot! Thanks so much!

**Comment by chrismcintosh** [comment]
> Either use `->profile()` or `->tools()` don't use both. 😀

Can confirm this fixes the issue I was having.

**Comment by fordiquez** [comment]
> > Either use `->profile()` or `->tools()` don't use both. 😀
> 
> Can confirm this fixes the issue I was having.

No, but it works if elements from `bubble_menu_tools` are contained in the `profiles` in the config file.

Like this:
`'minimal' => ['bold', 'italic', 'link', 'strike', 'underline', 'superscript', 'subscript', 'lead', 'small', 'bullet-list', 'ordered-list'],`
`'bubble_menu_tools' => ['bold', 'italic', 'strike', 'underline', 'superscript', 'subscript', 'lead', 'small', 'link'],`
