### ISSUE TITLE
maxLength / minLength (enhancements)

### ISSUE THREAD

**Issue by a-zog** [awcodes/filament-tiptap-editor#7]
Thank you for this great implementation of TipTap.

I wonder if you are planning to implement some of the basic textArea properties (min & max length + maybe rows/min-height).

Keep up the great work ! 🎉

**Comment by awcodes** [comment]
hey @a-zog,

I could possibly do something with min and max length, although generally when working with rich content like this it is for long form content that you'd usually not have those kinds of limits on.

As far as the height goes there are classes on the component that you can use to overwrite the styling to suit your needs, but since Tiptap doesn't work directly on a Textarea input it's not possible to use the rows() method to adjust the height of the editor.

**Comment by awcodes** [comment]
Support for minLength and maxLength has been added to latest release. v0.2.6
